default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL", 5) %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  host: <%= ENV.fetch("DB_HOST") %>
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEV", "nextfrotas360_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "nextfrotas360_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PROD", "nextfrotas360_production") %>
