default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch("PG_HOST") %>
  username: <%= ENV.fetch("PG_USER") %>
  password: <%= ENV.fetch("PG_PASSWORD") %>

development:
  <<: *default
  database: <%= ENV.fetch("PG_DATABASE_DEV") %>

test:
  <<: *default
  database: <%= ENV.fetch("PG_DATABASE_TEST") %>

production:
  <<: *default
  database: <%= ENV.fetch("PG_DATABASE_PROD") %>
